CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    owner_id VARCHAR NOT NULL REFERENCES users(id),
    speciality VARCHAR(255) NOT NULL
);