CREATE TABLE IF NOT EXISTS comments (
    id VARCHAR(255) UNIQUE NOT NULL,
    event_id VARCHAR(255) NOT NULL REFERENCES events(id),
    owner_id VARCHAR(255) NOT NULL REFERENCES users(id),
    text TEXT NOT NULL
);