CREATE TABLE IF NOT EXISTS comments (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int NOT NULL REFERENCES events(id),
    owner_id int NOT NULL REFERENCES users(id),
    text TEXT NOT NULL
);