CREATE TABLE IF NOT EXISTS fleamarket_posts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id int NOT NULL REFERENCES users(id),
    text TEXT NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    image VARCHAR(255)
);