CREATE TABLE IF NOT EXISTS petitions (
    id VARCHAR(255) UNIQUE NOT NULL,
    owner_id VARCHAR(255) NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0
);